### ISSUE TITLE
created black-face for Irileth

### ISSUE THREAD

**Issue by ntblood** [Synthesis-Collective/facefixer#11]
I found that facefixer synth patcher created black-face for Irileth. Without facefixer she looks bijin or pandorable

**Comment by Noggog** [comment]
Facefixer is one of the patchers that requires precise user input.  It needs to be configured with intention, and if done improperly can produce results that aren't desirable.    It just forwards what you tell it to.  Whether or not that's what's desired is up to you to decide and tweak.   If you think your user input is correct and it's the patcher making some mistake, you'll need to post more gritty specifics of your mods in question, the facefixer settings you have, and the specific reasoning for why you think it's doing it's job improperly.
