### ISSUE TITLE
Add ability to prioritize by order specified in json

### ISSUE THREAD

**Issue by Noggog** [Synthesis-Collective/facefixer#3]

**Comment by jdsmith2816** [comment]
What is the value in that?  The json is just a list of plugins to care about.  Load order is determing everything else.  I feel like having to care about load order and json order would lead to mistakes.

**Comment by Noggog** [comment]
Was just a feature request made by someone in discord.   Obviously I'm don't use the tools myself to know exactly how they should be used.. but I saw facefixer as a way to break normal rules and reach back to grab faces that a user specifically wanted that normally wouldn't be used.   You're given the power to specify which faces specifically you want, irregardless of normal winning override mechanics.  

This I saw as just an extension of that.  You might need to have XYZ in a certain order for other winning record reasons for other stats, etc, but still want all the faces from X mainly?  Who knows if that's actually a situation that comes up in real life.. but the theory made sense to me in passing.  I was thinking it could just be an optional setting, as yeah, by default it'll just cause bugs for people unless they know what they're doing.

**Comment by sean-kang** [comment]
Also, the face fixer brings the records from the smashed patch - that may have the mixture of the face data from multiple mods - and it will overwrite any previous records. There is no way to prevent this problem from happening at the moment. If the order of the face-related plugins can be specified in the settings, it will be able to avoid the problem easily.

**Comment by Noggog** [comment]
This feature is already complete, and exposed via the "Prioritize By Specified Order" checkbox in the UI settings
